version: "3"

networks:
    projects:
        driver: 'bridge'
        ipam:
            config:
                - subnet: 172.32.122.0/24

services:
    php:
        build:
            context: ./php
        container_name: docker_php
        expose:
            - 9000
            - 9003
        volumes:
            - ../workspace:/projects
        networks:
            - projects
    nginx:
        image: nginx:latest
        container_name: docker_nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./nginx/sites:/etc/nginx/sites-available
            - ../workspace:/projects
        ports:
            - 80:80
            - 443:443
        networks:
            projects:
                ipv4_address: 172.32.122.22
    mysql:
        build:
            context: ./mysql
        container_name: docker_mysql
        ports:
            - 3306:3306
        volumes:
            - ../data/mysql:/var/lib/mysql
            - ../mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=projects
            # - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - projects